---
name: CI

on:
  push:

jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: dojo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
  StaticCodeAnalysisTests:
    runs-on: ubuntu-latest
    needs:
      - Lint
    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
            pip install -r requirements.txt

  UnitTests:
    runs-on: ubuntu-latest
    needs:
      - StaticCodeAnalysisTests
    steps:
      - run: echo "example"
      - run: echo "does it work ?"

  Build:
    runs-on: ubuntu-latest
    needs:
      - UnitTests
    steps:
      - run: echo "example"
      - run: echo "does it work ?"

  IntegTests:
    runs-on: ubuntu-latest
    needs:
      - Build
    steps:
      - run: echo "example"
      - run: echo "does it work ?"
