---
name: CI

on:
  push:

jobs:
  Lint:
    runs-on: ubuntu-latest
    #steps:
      #- run: echo "example"
      #- run: echo "does it work ?"
     steps:
      - uses: actions/checkout@v2  
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "src"
          mypy-options: "--ignore-missing-imports --show-error-codes"
          pylint-options: "--rcfile=setup.cfg"
          isort-options: "-w 100"
          django: true
